### ISSUE TITLE
Zero division

### ISSUE THREAD

**Issue by lourdesalo** [zhangtaolab/Jazz#1]
Hello!

This is my first time using Jazz. 
This is the error i get: 

```
got exception in Jazzlib.FRegion.filter_region: ZeroDivisionError('division by zero'), terminating the pool
pool is terminated
Traceback (most recent call last):
  File "/home/Lourdes/MHS_seq/Jazz/Jazz.py", line 367, in <module>
    main()
  File "/home/Lourdes/MHS_seq/Jazz/Jazz.py", line 29, in main
    withcontrol(opt)
  File "/home/Lourdes/MHS_seq/Jazz/Jazz.py", line 59, in withcontrol
    inputfregion = FRegion(bamfile=inputfile, jobtype=jobtype, countchr=count_chr, nthreads=nthreads, maxinsert=maxinsert)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Lourdes/MHS_seq/Jazz/Jazzlib/FRegion.py", line 30, in __init__
    self.__filte_region()
  File "/home/Lourdes/MHS_seq/Jazz/Jazzlib/FRegion.py", line 47, in filte_region
    filted_region = res['filted_region']
                    ~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

These same bam files work well using MACS2. 

Another thing, upon installation, I got this error 

`Traceback (most recent call last):
  File "/home/Lourdes/MHS_seq/Jazz/Jazz.py", line 12, in <module>
    from Jazzlib.sta import *
  File "/home/Lourdes/MHS_seq/Jazz/Jazzlib/sta.py", line 4, in <module>
    from scipy import math
ImportError: cannot import name 'math' from 'scipy' (/home/Lourdes/bin/anaconda3/lib/python3.11/site-packages/scipy/__init__.py)`

I simply deleted "scipy import math" for the code to work. Im unsure if these two issues could be related.

Please advise!

Lourdes

**Comment by lourdesalo** [comment]
I fixed this by getting rid of unmapped reads from my bam file using `samtools view -F 4`
